/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PSViewController.h"
#import "PSViewControllerOffsetProtocol.h"

@class UIActionSheet, UIAlertView, UIKeyboard, UIPopoverController, NSMutableDictionary, UITableView, NSArray, NSMutableArray, NSString;

@interface PSListController : PSViewController <UITableViewDelegate, UITableViewDataSource, UIActionSheetDelegate, UIAlertViewDelegate, UIPopoverControllerDelegate, PSViewControllerOffsetProtocol> {
	NSMutableDictionary *_cells;	// 164 = 0xa4
	BOOL _cachesCells;	// 168 = 0xa8
	BOOL _forceSynchronousIconLoadForCreatedCells;	// 169 = 0xa9
	UITableView *_table;	// 172 = 0xac
	NSArray *_specifiers;	// 176 = 0xb0
	NSMutableDictionary *_specifiersByID;	// 180 = 0xb4
	NSMutableArray *_groups;	// 184 = 0xb8
	NSString *_specifierID;	// 188 = 0xbc
	NSMutableArray *_bundleControllers;	// 192 = 0xc0
	BOOL _bundlesLoaded;	// 196 = 0xc4
	BOOL _showingSetupController;	// 197 = 0xc5
	UIActionSheet *_actionSheet;	// 200 = 0xc8
	UIAlertView *_alertView;	// 204 = 0xcc
	BOOL _swapAlertButtons;	// 208 = 0xd0
	BOOL _keyboardWasVisible;	// 209 = 0xd1
	UIKeyboard *_keyboard;	// 212 = 0xd4
	UIPopoverController *_popupStylePopoverController;	// 216 = 0xd8
	BOOL _popupStylePopoverShouldRePresent;	// 220 = 0xdc
	BOOL _popupIsModal;	// 221 = 0xdd
	BOOL _popupIsDismissing;	// 222 = 0xde
	BOOL _hasAppeared;	// 223 = 0xdf
	float _verticalContentOffset;	// 224 = 0xe0
	NSString *_offsetItemName;	// 228 = 0xe4
	CGPoint _contentOffsetWithKeyboard;	// 232 = 0xe8
}
@property(assign, nonatomic) BOOL forceSynchronousIconLoadForCreatedCells;	// G=0x2151; S=0x2161; @synthesize=_forceSynchronousIconLoadForCreatedCells
@property(retain) NSString *specifierID;	// G=0x2101; S=0x587d; converted property
@property(retain) NSArray *specifiers;	// G=0x8f25; S=0x8d35; converted property
@property(readonly, retain) UITableView *table;	// G=0x20c9; converted property
@property(readonly, assign) float verticalContentOffset;	// G=0x234d; converted property
+ (BOOL)displaysButtonBar;	// 0x20c5
- (id)init;	// 0x60e5
- (id)initForContentSize:(CGSize)contentSize;	// 0x60d5
- (void)_addIdentifierForSpecifier:(id)specifier;	// 0x8de1
- (id)_createGroupIndices:(id)indices;	// 0x5cc5
- (id)_customViewForSpecifier:(id)specifier class:(Class)aClass isHeader:(BOOL)header;	// 0x5045
- (BOOL)_getGroup:(int *)group row:(int *)row ofSpecifierAtIndex:(int)index groups:(id)groups;	// 0x8595
- (float)_getKeyboardIntersectionHeight;	// 0x2ab1
- (void)_insertContiguousSpecifiers:(id)specifiers atIndex:(int)index animated:(BOOL)animated;	// 0x7c05
- (void)_keyboardDidHide:(id)_keyboard;	// 0x23e1
- (void)_keyboardWillHide:(id)_keyboard;	// 0x23f5
- (void)_keyboardWillShow:(id)_keyboard;	// 0x2625
- (void)_loadBundleControllers;	// 0x6515
- (int)_nextGroupInSpecifiersAfterIndex:(int)specifiersAfterIndex inArray:(id)array;	// 0x7049
- (void)_removeContiguousSpecifiers:(id)specifiers animated:(BOOL)animated;	// 0x720d
- (void)_removeIdentifierForSpecifier:(id)specifier;	// 0x8da1
- (void)_returnKeyPressed:(id)pressed;	// 0x4259
- (void)_setContentInset:(float)inset;	// 0x2a2d
- (void)_setNotShowingSetupController;	// 0x213d
- (float)_tableView:(id)view heightForCustomInSection:(int)section isHeader:(BOOL)header;	// 0x4ed9
- (id)_tableView:(id)view viewForCustomInSection:(int)section isHeader:(BOOL)header;	// 0x4e25
- (void)_unloadBundleControllers;	// 0x649d
- (void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;	// 0x3a39
- (void)addSpecifier:(id)specifier;	// 0x79d1
- (void)addSpecifier:(id)specifier animated:(BOOL)animated;	// 0x797d
- (void)addSpecifiersFromArray:(id)array;	// 0x7969
- (void)addSpecifiersFromArray:(id)array animated:(BOOL)animated;	// 0x7915
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;	// 0x3ae9
- (Class)backgroundViewClass;	// 0x609d
- (void)beginUpdates;	// 0x8c55
- (id)bundle;	// 0x228d
- (id)cachedCellForSpecifier:(id)specifier;	// 0x56fd
- (id)cachedCellForSpecifierID:(id)specifierID;	// 0x56cd
- (void)clearCache;	// 0x90c9
- (void)confirmationViewAcceptedForSpecifier:(id)specifier;	// 0x3c1d
- (void)confirmationViewCancelledForSpecifier:(id)specifier;	// 0x3bd5
- (BOOL)containsSpecifier:(id)specifier;	// 0x8791
- (id)contentScrollView;	// 0x20f1
- (id)controllerForRowAtIndexPath:(id)indexPath;	// 0x3649
- (void)createGroupIndices;	// 0x5c69
- (void)dealloc;	// 0x6205
- (id)description;	// 0x21fd
- (void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;	// 0x4c35
- (void)dismissPopover;	// 0x31b1
- (void)dismissPopoverAnimated:(BOOL)animated;	// 0x3169
- (void)endUpdates;	// 0x8c35
- (id)findFirstVisibleResponder;	// 0x4895
// declared property getter: - (BOOL)forceSynchronousIconLoadForCreatedCells;	// 0x2151
- (void)formSheetViewWillDisappear;	// 0x43f9
- (BOOL)getGroup:(int *)group row:(int *)row ofSpecifier:(id)specifier;	// 0x8615
- (BOOL)getGroup:(int *)group row:(int *)row ofSpecifierAtIndex:(int)index;	// 0x8511
- (BOOL)getGroup:(int *)group row:(int *)row ofSpecifierID:(id)specifierID;	// 0x8669
- (void)handleURL:(id)url;	// 0x2e09
- (int)indexForIndexPath:(id)indexPath;	// 0x8c75
- (int)indexForRow:(int)row inGroup:(int)group;	// 0x84d1
- (int)indexOfGroup:(int)group;	// 0x873d
- (int)indexOfSpecifier:(id)specifier;	// 0x87b5
- (int)indexOfSpecifierID:(id)specifierID;	// 0x87e5
- (id)indexPathForIndex:(int)index;	// 0x8ce9
- (void)insertContiguousSpecifiers:(id)specifiers afterSpecifier:(id)specifier;	// 0x7a2d
- (void)insertContiguousSpecifiers:(id)specifiers afterSpecifier:(id)specifier animated:(BOOL)animated;	// 0x7b6d
- (void)insertContiguousSpecifiers:(id)specifiers afterSpecifierID:(id)anId;	// 0x7a09
- (void)insertContiguousSpecifiers:(id)specifiers afterSpecifierID:(id)anId animated:(BOOL)animated;	// 0x7b15
- (void)insertContiguousSpecifiers:(id)specifiers atEndOfGroup:(int)group;	// 0x79e5
- (void)insertContiguousSpecifiers:(id)specifiers atEndOfGroup:(int)group animated:(BOOL)animated;	// 0x7a75
- (void)insertContiguousSpecifiers:(id)specifiers atIndex:(int)index;	// 0x7a51
- (void)insertContiguousSpecifiers:(id)specifiers atIndex:(int)index animated:(BOOL)animated;	// 0x7be1
- (void)insertSpecifier:(id)specifier afterSpecifier:(id)specifier2;	// 0x81ed
- (void)insertSpecifier:(id)specifier afterSpecifier:(id)specifier2 animated:(BOOL)animated;	// 0x8311
- (void)insertSpecifier:(id)specifier afterSpecifierID:(id)anId;	// 0x81c9
- (void)insertSpecifier:(id)specifier afterSpecifierID:(id)anId animated:(BOOL)animated;	// 0x82d5
- (void)insertSpecifier:(id)specifier atEndOfGroup:(int)group;	// 0x81a5
- (void)insertSpecifier:(id)specifier atEndOfGroup:(int)group animated:(BOOL)animated;	// 0x8235
- (void)insertSpecifier:(id)specifier atIndex:(int)index;	// 0x8211
- (void)insertSpecifier:(id)specifier atIndex:(int)index animated:(BOOL)animated;	// 0x837d
- (id)loadSpecifiersFromPlistName:(id)plistName target:(id)target;	// 0x8fc1
- (void)loadView;	// 0x5e0d
- (void)loseFocus;	// 0x5c0d
- (int)numberOfGroups;	// 0x86fd
- (int)numberOfSectionsInTableView:(id)tableView;	// 0x5811
- (BOOL)performActionForSpecifier:(id)specifier;	// 0x4125
- (BOOL)performCancelForSpecifier:(id)specifier;	// 0x3ff1
- (void)popoverController:(id)controller animationCompleted:(int)completed;	// 0x31c5
- (BOOL)popoverControllerShouldDismissPopover:(id)popoverController;	// 0x2111
- (void)popupViewWillDisappear;	// 0x43b9
- (void)prepareSpecifiersMetadata;	// 0x45a9
- (void)pushController:(id)controller;	// 0x3155
- (void)pushController:(id)controller animate:(BOOL)animate;	// 0x320d
- (void)reload;	// 0x5b59
- (void)reloadIconForSpecifierForBundle:(id)bundle;	// 0x2cf5
- (void)reloadSpecifier:(id)specifier;	// 0x8871
- (void)reloadSpecifier:(id)specifier animated:(BOOL)animated;	// 0x8885
- (void)reloadSpecifierAtIndex:(int)index;	// 0x88d1
- (void)reloadSpecifierAtIndex:(int)index animated:(BOOL)animated;	// 0x88e5
- (void)reloadSpecifierID:(id)anId;	// 0x8829
- (void)reloadSpecifierID:(id)anId animated:(BOOL)animated;	// 0x883d
- (void)reloadSpecifiers;	// 0x58bd
- (void)removeContiguousSpecifiers:(id)specifiers;	// 0x71e9
- (void)removeContiguousSpecifiers:(id)specifiers animated:(BOOL)animated;	// 0x71fd
- (void)removeLastSpecifier;	// 0x77bd
- (void)removeLastSpecifierAnimated:(BOOL)animated;	// 0x7775
- (void)removeSpecifier:(id)specifier;	// 0x77f9
- (void)removeSpecifier:(id)specifier animated:(BOOL)animated;	// 0x78ad
- (void)removeSpecifierAtIndex:(int)index;	// 0x77d1
- (void)removeSpecifierAtIndex:(int)index animated:(BOOL)animated;	// 0x780d
- (void)removeSpecifierID:(id)anId;	// 0x77e5
- (void)removeSpecifierID:(id)anId animated:(BOOL)animated;	// 0x7879
- (void)replaceContiguousSpecifiers:(id)specifiers withSpecifiers:(id)specifiers2;	// 0x71c5
- (void)replaceContiguousSpecifiers:(id)specifiers withSpecifiers:(id)specifiers2 animated:(BOOL)animated;	// 0x70a5
- (void)returnPressedAtEnd;	// 0x4329
- (int)rowsForGroup:(int)group;	// 0x848d
- (void)selectRowForSpecifier:(id)specifier;	// 0x237d
- (void)setCachesCells:(BOOL)cells;	// 0x2181
- (void)setDesiredVerticalContentOffset:(float)offset;	// 0x2129
- (void)setDesiredVerticalContentOffsetItemNamed:(id)named;	// 0x230d
// declared property setter: - (void)setForceSynchronousIconLoadForCreatedCells:(BOOL)createdCells;	// 0x2161
// converted property setter: - (void)setSpecifierID:(id)anId;	// 0x587d
// converted property setter: - (void)setSpecifiers:(id)specifiers;	// 0x8d35
- (void)setTitle:(id)title;	// 0x5851
- (BOOL)shouldReloadSpecifiersOnResume;	// 0x2139
- (BOOL)shouldSelectResponderOnAppearance;	// 0x4969
- (void)showConfirmationSheetForSpecifier:(id)specifier;	// 0x3c65
- (void)showConfirmationViewForSpecifier:(id)specifier;	// 0x3cbd
- (void)showConfirmationViewForSpecifier:(id)specifier useAlert:(BOOL)alert swapAlertButtons:(BOOL)buttons;	// 0x3d19
- (id)specifier;	// 0x20d9
- (id)specifierAtIndex:(int)index;	// 0x86b1
- (id)specifierForID:(id)anId;	// 0x3509
// converted property getter: - (id)specifierID;	// 0x2101
// converted property getter: - (id)specifiers;	// 0x8f25
- (id)specifiersInGroup:(int)group;	// 0x8405
// converted property getter: - (id)table;	// 0x20c9
- (id)tableBackgroundColor;	// 0x6069
- (int)tableStyle;	// 0x20ed
- (id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;	// 0x54cd
- (id)tableView:(id)view detailTextForHeaderInSection:(int)section;	// 0x52a5
- (void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;	// 0x3569
- (float)tableView:(id)view heightForFooterInSection:(int)section;	// 0x4db9
- (float)tableView:(id)view heightForHeaderInSection:(int)section;	// 0x4e01
- (float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;	// 0x5411
- (int)tableView:(id)view numberOfRowsInSection:(int)section;	// 0x574d
- (int)tableView:(id)view titleAlignmentForFooterInSection:(int)section;	// 0x50e1
- (int)tableView:(id)view titleAlignmentForHeaderInSection:(int)section;	// 0x517d
- (id)tableView:(id)view titleForFooterInSection:(int)section;	// 0x5219
- (id)tableView:(id)view titleForHeaderInSection:(int)section;	// 0x5395
- (id)tableView:(id)view viewForFooterInSection:(int)section;	// 0x4d95
- (id)tableView:(id)view viewForHeaderInSection:(int)section;	// 0x4ddd
- (Class)tableViewClass;	// 0x60b9
- (void)updateSpecifiers:(id)specifiers withSpecifiers:(id)specifiers2;	// 0x6fa1
- (void)updateSpecifiersInRange:(NSRange)range withSpecifiers:(id)specifiers;	// 0x6591
// converted property getter: - (float)verticalContentOffset;	// 0x234d
- (void)viewDidAppear:(BOOL)view;	// 0x4495
- (void)viewDidLoad;	// 0x478d
- (void)viewDidUnload;	// 0x5d7d
- (void)viewWillAppear:(BOOL)view;	// 0x4a09
- (void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;	// 0x4d41
@end

@interface PSListController (PasscodeAdditions)
- (id)popupStylePopoverController;	// 0x2171
- (void)showPINSheet:(id)sheet;	// 0x9289
@end

