/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PSController.h"

@class PSSpecifier, NSMutableSet;

@interface PSRootController : UINavigationController <PSController, UINavigationControllerDelegate> {
	PSSpecifier *_specifier;	// 232 = 0xe8
	NSMutableSet *_tasks;	// 236 = 0xec
	BOOL _deallocating;	// 240 = 0xf0
	unsigned char _hasTelephony;	// 241 = 0xf1
}
@property(readonly, assign) BOOL deallocating;	// G=0x10aa1; converted property
@property(retain) id parentController;	// G=0x10ab1; S=0x10a81; converted property
@property(retain) id rootController;	// G=0x10ab9; S=0x10ab5; converted property
@property(retain) PSSpecifier *specifier;	// G=0x10a85; S=0x12631; converted property
+ (BOOL)processedBundle:(id)bundle parentController:(id)controller parentSpecifier:(id)specifier bundleControllers:(id *)controllers settings:(id)settings;	// 0x10ae1
+ (id)readPreferenceValue:(id)value;	// 0x10fe9
+ (void)setPreferenceValue:(id)value specifier:(id)specifier;	// 0x11345
+ (void)writePreference:(id)preference;	// 0x113cd
- (id)initWithTitle:(id)title identifier:(id)identifier;	// 0x12911
- (void)_delayedControllerReleaseAfterPop:(id)pop;	// 0x11b35
- (void)addTask:(id)task;	// 0x1279d
- (BOOL)busy;	// 0x126b5
- (BOOL)canBeShownFromSuspendedState;	// 0x10abd
- (id)contentViewForTopController;	// 0x12679
- (void)dealloc;	// 0x11ef1
// converted property getter: - (BOOL)deallocating;	// 0x10aa1
- (void)didDismissFormSheetView;	// 0x11ba9
- (void)didDismissPopupView;	// 0x11c71
- (void)didLock;	// 0x1217d
- (void)didUnlock;	// 0x12115
- (void)didWake;	// 0x120e1
- (void)handleURL:(id)url;	// 0x10a95
- (void)lazyLoadBundle:(id)bundle;	// 0x11d39
- (void)navigationController:(id)controller willShowViewController:(id)controller2 animated:(BOOL)animated;	// 0x115d5
// converted property getter: - (id)parentController;	// 0x10ab1
- (id)popToRootViewControllerAnimated:(BOOL)rootViewControllerAnimated;	// 0x118cd
- (id)popToViewController:(id)viewController animated:(BOOL)animated;	// 0x119cd
- (id)popViewControllerAnimated:(BOOL)animated;	// 0x11acd
- (void)pushController:(id)controller;	// 0x125c1
- (id)readPreferenceValue:(id)value;	// 0x12a69
// converted property getter: - (id)rootController;	// 0x10ab9
- (void)sendWillBecomeActive;	// 0x121e5
- (void)sendWillResignActive;	// 0x1222d
// converted property setter: - (void)setParentController:(id)controller;	// 0x10a81
- (void)setPreferenceValue:(id)value specifier:(id)specifier;	// 0x10ac1
// converted property setter: - (void)setRootController:(id)controller;	// 0x10ab5
// converted property setter: - (void)setSpecifier:(id)specifier;	// 0x12631
- (void)setViewControllers:(id)controllers animated:(BOOL)animated;	// 0x116ed
- (void)showLeftButton:(id)button withStyle:(int)style rightButton:(id)button3 withStyle:(int)style4;	// 0x1243d
// converted property getter: - (id)specifier;	// 0x10a85
- (id)specifiers;	// 0x10a79
- (void)statusBarWillAnimateByHeight:(float)statusBar;	// 0x10a7d
- (void)statusBarWillChangeHeight:(id)statusBar;	// 0x12275
- (void)suspend;	// 0x121b1
- (void)taskFinished:(id)finished;	// 0x126e5
- (BOOL)taskIsRunning:(id)running;	// 0x127f1
- (id)tasksDescription;	// 0x12819
- (void)willBecomeActive;	// 0x10a9d
- (void)willDismissFormSheetView;	// 0x11c0d
- (void)willDismissPopupView;	// 0x11cd5
- (void)willResignActive;	// 0x10a99
- (void)willUnlock;	// 0x12149
@end

