/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

@class NSMutableDictionary, NSArray, NSDictionary, NSString;

@interface PSSpecifier : NSObject {
	id target;	// 4 = 0x4
	SEL getter;	// 8 = 0x8
	SEL setter;	// 12 = 0xc
	SEL action;	// 16 = 0x10
	SEL cancel;	// 20 = 0x14
	Class detailControllerClass;	// 24 = 0x18
	int cellType;	// 28 = 0x1c
	Class editPaneClass;	// 32 = 0x20
	int keyboardType;	// 36 = 0x24
	int autoCapsType;	// 40 = 0x28
	int autoCorrectionType;	// 44 = 0x2c
	int textFieldType;	// 48 = 0x30
	NSString *_name;	// 52 = 0x34
	NSArray *_values;	// 56 = 0x38
	NSDictionary *_titleDict;	// 60 = 0x3c
	NSDictionary *_shortTitleDict;	// 64 = 0x40
	id _userInfo;	// 68 = 0x44
	NSMutableDictionary *_properties;	// 72 = 0x48
}
@property(assign, nonatomic) int cellType;	// G=0x977d; S=0x978d; @synthesize
@property(assign, nonatomic) Class detailControllerClass;	// G=0x979d; S=0x97ad; @synthesize
@property(assign, nonatomic) Class editPaneClass;	// G=0x975d; S=0x976d; @synthesize
@property(retain, nonatomic) NSString *identifier;	// G=0x9b9d; S=0x9c1d; 
@property(retain, nonatomic) NSString *name;	// G=0x971d; S=0x9b3d; @synthesize=_name
@property(retain) NSMutableDictionary *properties;	// G=0x969d; S=0xa1b1; converted property
@property(retain, nonatomic) NSDictionary *shortTitleDictionary;	// G=0x96ad; S=0x9aed; @synthesize=_shortTitleDict
@property(assign, nonatomic) id target;	// G=0x97bd; S=0x97cd; @synthesize
@property(retain, nonatomic) NSDictionary *titleDictionary;	// G=0x973d; S=0x9ac5; @synthesize=_titleDict
@property(retain, nonatomic) id userInfo;	// G=0x974d; S=0x9a9d; @synthesize=_userInfo
@property(retain, nonatomic) NSArray *values;	// G=0x972d; S=0x9b15; @synthesize=_values
+ (int)autoCapsTypeForString:(id)string;	// 0x9909
+ (int)autoCorrectionTypeForNumber:(id)number;	// 0x9971
+ (id)emptyGroupSpecifier;	// 0x9999
+ (id)groupSpecifierWithName:(id)name;	// 0x99ad
+ (int)keyboardTypeForString:(id)string;	// 0x98b9
+ (id)preferenceSpecifierNamed:(id)named target:(id)target set:(SEL)set get:(SEL)get detail:(Class)detail cell:(int)cell edit:(Class)edit;	// 0x99e1
- (id)init;	// 0x982d
// declared property getter: - (int)cellType;	// 0x977d
- (void)dealloc;	// 0x9d1d
- (id)description;	// 0x9c39
// declared property getter: - (Class)detailControllerClass;	// 0x979d
// declared property getter: - (Class)editPaneClass;	// 0x975d
// declared property getter: - (id)identifier;	// 0x9b9d
- (void)loadValuesAndTitlesFromDataSource;	// 0xa0f5
// declared property getter: - (id)name;	// 0x971d
// converted property getter: - (id)properties;	// 0x969d
- (id)propertyForKey:(id)key;	// 0xa245
- (void)removePropertyForKey:(id)key;	// 0xa1f1
// declared property setter: - (void)setCellType:(int)type;	// 0x978d
// declared property setter: - (void)setDetailControllerClass:(Class)aClass;	// 0x97ad
// declared property setter: - (void)setEditPaneClass:(Class)aClass;	// 0x976d
// declared property setter: - (void)setIdentifier:(id)identifier;	// 0x9c1d
- (void)setKeyboardType:(int)type autoCaps:(int)caps autoCorrection:(int)correction;	// 0x96d1
// declared property setter: - (void)setName:(id)name;	// 0x9b3d
// converted property setter: - (void)setProperties:(id)properties;	// 0xa1b1
- (void)setProperty:(id)property forKey:(id)key;	// 0xa215
// declared property setter: - (void)setShortTitleDictionary:(id)dictionary;	// 0x9aed
// declared property setter: - (void)setTarget:(id)target;	// 0x97cd
// declared property setter: - (void)setTitleDictionary:(id)dictionary;	// 0x9ac5
// declared property setter: - (void)setUserInfo:(id)info;	// 0x9a9d
// declared property setter: - (void)setValues:(id)values;	// 0x9b15
- (void)setValues:(id)values titles:(id)titles;	// 0xa0d1
- (void)setValues:(id)values titles:(id)titles shortTitles:(id)titles3;	// 0x9f85
- (void)setupIconImageWithBundle:(id)bundle;	// 0x9e65
- (void)setupIconImageWithPath:(id)path;	// 0x9dcd
// declared property getter: - (id)shortTitleDictionary;	// 0x96ad
// declared property getter: - (id)target;	// 0x97bd
- (int)titleCompare:(id)compare;	// 0x9b65
// declared property getter: - (id)titleDictionary;	// 0x973d
// declared property getter: - (id)userInfo;	// 0x974d
// declared property getter: - (id)values;	// 0x972d
@end

